graphql:
  servlet:
    enabled: true
    mapping: /graphql
    corsEnabled: true
    cors:
      allowed-methods: GET, HEAD, POST
    async-mode-enabled: true

graphiql:
  mapping: /graphiql
  static:
    basePath: /
  enabled: true
  pageTitle: GraphiQL